<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <SignAssembly>false</SignAssembly>

    <AssemblyName>AngleSharp.Css</AssemblyName>
    <RootNamespace>AngleSharp.Css</RootNamespace>
    <Nullable>disable</Nullable>
    <AssemblyOriginatorKeyFile>Key.snk</AssemblyOriginatorKeyFile>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <RepositoryUrl>https://github.com/AngleSharp/AngleSharp.Css</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <TargetFramework>netstandard2.1</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All" />
  </ItemGroup>

  <ItemGroup>
        <ProjectReference Include="..\AngleSharp\AngleSharp.Core.csproj" />
    <ProjectReference Include="..\LayoutEngine.Contracts.AngleSharp\LayoutEngine.Contracts.AngleSharp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="LayoutEngine.Platform.Tests" />
    <InternalsVisibleTo Include="AngleSharp.Core.Tests" />
    <InternalsVisibleTo Include="AngleSharp.Css.Tests" />
  </ItemGroup>

  <PropertyGroup Condition=" '$(OS)' == 'Windows_NT' ">
    <DelaySign>false</DelaySign>
  </PropertyGroup>
</Project>
