<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <SignAssembly>true</SignAssembly>
      <AssemblyOriginatorKeyFile>..\LayoutEngine.snk</AssemblyOriginatorKeyFile>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="DI\" />
      <Folder Include="Integration\" />
      <Folder Include="Internal\Invalidation\" />
      <Folder Include="Internal\Monitoring\" />
      <Folder Include="Internal\Utilities\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="10.0.0-preview.1.25080.5" />
      <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="10.0.0-preview.1.25080.5" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.0-preview.1.25080.5" />
      <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="10.0.0-preview.1.25080.5" />
    </ItemGroup>

<!--  <ItemGroup>-->
<!--    <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleTo">-->
<!--      <_Parameter1>Infrastructure.CacheManager.Tests, PublicKey=0602000000a40000525341310008000001000100e167f0c0d1b79dd3e1f9f4beabfebfdb673ab0ef8bd64ada3a1835535bda74973c80fa2fd490185ad4baf2b9ed7cd1554d24529f1c3b057b1fc8e33ae63f9c9f815ad1d5f4d1c846a18a440c2d094b1af40f0eed044555427b675e8c9f5c86ab0f8500881bc77321e8d3bc47e8f6ee4887680e3120752f6f10e29b4861f731199ceee544ac6b810fb3a4192a807a60319cd5a65787338291520868b518bddbcc88d9010de8e931c46ef47ff90afb7d9006e42538ab462931afadb2df213fca173e0fde2aa9f5e2da17e963e8dde27340aaa902d634fe8378ce9e7ac42dd8fd6707fad0e731d6c54f83ad5b18e20b6c2fe91e8081491c6cfacebeb8de6e618aa0</_Parameter1>-->
<!--    </AssemblyAttribute>-->
<!--  </ItemGroup>-->

</Project>
