<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AngleSharp.Css\AngleSharp.Css.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Util\" />
    </ItemGroup>

</Project>
