namespace LayoutEngine.NG.Layout;

using AngleSharp.Dom;
using LayoutEngine.NG.Style;

/// <summary>
/// Represents a node in the layout tree, following LayoutNG conventions.
/// In LayoutNG, LayoutObject is the base class for all objects in the layout tree
/// and corresponds to a DOM node that generates a box.
/// </summary>
public class LayoutObject
{
    /// <summary>
    /// The DOM node associated with this layout object.
    /// In BlinkNG, not all DOM nodes have layout objects (e.g., display:none).
    /// </summary>
    public INode? Node { get; set; }

    /// <summary>
    /// The computed style for this layout object.
    /// In BlinkNG, this is the result of style resolution.
    /// </summary>
    public ComputedStyle? Style { get; set; }

    /// <summary>
    /// Parent in the layout tree.
    /// In LayoutNG, the layout tree structure may differ from the DOM tree.
    /// </summary>
    public LayoutObject? Parent { get; set; }

    /// <summary>
    /// First child in the layout tree.
    /// LayoutNG uses a linked list structure for children.
    /// </summary>
    public LayoutObject? FirstChild { get; set; }

    /// <summary>
    /// Next sibling in the layout tree.
    /// </summary>
    public LayoutObject? NextSibling { get; set; }

    /// <summary>
    /// Previous sibling in the layout tree.
    /// </summary>
    public LayoutObject? PreviousSibling { get; set; }

    /// <summary>
    /// Whether this object needs layout.
    /// In LayoutNG, this is part of the dirty bit system.
    /// </summary>
    public bool NeedsLayout { get; set; } = true;

    /// <summary>
    /// Whether this object's paint properties are dirty.
    /// In BlinkNG, paint invalidation is separate from layout.
    /// </summary>
    public bool NeedsPaint { get; set; } = true;

    /// <summary>
    /// The fragment(s) generated by this layout object.
    /// In LayoutNG, layout objects produce fragments during layout.
    /// Note: In real LayoutNG, this would be more complex to handle fragmentation.
    /// </summary>
    public Fragment? Fragment { get; set; }

    /// <summary>
    /// Gets the layout object type based on the computed style.
    /// In LayoutNG, this determines which layout algorithm to use.
    /// </summary>
    public virtual LayoutObjectType GetLayoutObjectType()
    {
        if (Style == null)
            return LayoutObjectType.Unknown;

        return Style.Display switch
        {
            DisplayType.Block => LayoutObjectType.Block,
            DisplayType.Inline => LayoutObjectType.Inline,
            DisplayType.InlineBlock => LayoutObjectType.InlineBlock,
            DisplayType.Flex => LayoutObjectType.FlexContainer,
            DisplayType.Grid => LayoutObjectType.GridContainer,
            DisplayType.Table => LayoutObjectType.Table,
            DisplayType.None => LayoutObjectType.None,
            _ => LayoutObjectType.Unknown
        };
    }

    /// <summary>
    /// Whether this layout object establishes a new formatting context.
    /// In LayoutNG, this affects how descendants are laid out.
    /// </summary>
    public virtual bool EstablishesFormattingContext()
    {
        // Simplified version - in real LayoutNG this is more complex
        var type = GetLayoutObjectType();
        return type == LayoutObjectType.Block ||
               type == LayoutObjectType.FlexContainer ||
               type == LayoutObjectType.GridContainer ||
               type == LayoutObjectType.Table;
    }
}

/// <summary>
/// Types of layout objects, following LayoutNG's classification.
/// </summary>
public enum LayoutObjectType
{
    Unknown,
    None,
    View,        // LayoutView - the document root
    Box,         // LayoutBox - base box type
    Block,       // Block-level box
    Inline,      // Inline-level box
    InlineBlock, // Inline-block box
    Text,        // Text node

    // Complex layout types (to be implemented later)
    FlexContainer,
    FlexItem,
    GridContainer,
    GridItem,
    Table,
    TableRow,
    TableCell,
}