<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
      <SignAssembly>false</SignAssembly>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AngleSharp.Css\AngleSharp.Css.csproj" />
      <ProjectReference Include="..\AngleSharp\AngleSharp.Core.csproj" />
      <ProjectReference Include="..\LayoutEngine.StyleSystem\LayoutEngine.StyleSystem.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.0-preview.1.25080.5" />
    </ItemGroup>

</Project>
