<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>netstandard2.1</TargetFramework>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\AngleSharp.Css\AngleSharp.Css.csproj" />
      <ProjectReference Include="..\AngleSharp\AngleSharp.Core.csproj" />
      <ProjectReference Include="..\LayoutEngine.Contracts.AngleSharp\LayoutEngine.Contracts.AngleSharp.csproj" />
    </ItemGroup>

</Project>
