<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFrameworks>net6.0</TargetFrameworks>
        <ImplicitUsings>disable</ImplicitUsings>
        <Nullable>disable</Nullable>

        <IsPackable>false</IsPackable>
        <LangVersion>9</LangVersion>
        <AssemblyName>AngleSharp.Renderer.Tests</AssemblyName>
        <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.2.0"/>
        <PackageReference Include="coverlet.collector" Version="6.0.0"/>
        <PackageReference Include="NUnit" Version="3.14.0" />
        <PackageReference Include="NUnit3TestAdapter" Version="4.2.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\AngleSharp.Css\AngleSharp.Css.csproj" />
      <ProjectReference Include="..\AngleSharp.Renderer\AngleSharp.Renderer.csproj" />
      <ProjectReference Include="..\AngleSharp\AngleSharp.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Update="TestData\test_block_element_takes_full_container_width.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\test_vertical_margins_collapse_between_siblings.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\test_explicit_height_overrides_content_height.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\test_padding_reduces_available_content_width.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\test_percentage_width_resolves_relative_to_container.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\test_border_increases_total_width.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\test_display_inline_not_handled_by_block_strategy.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\test_display_none_skips_layout.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\test_inline_block_baseline_alignment.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\test_inline_block_retains_dimensions_in_inline_flow.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\test_max_width_constrains_content_width.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\test_min_width_overrides_content_width.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\test_overflow_hidden_clips_child.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\test_percent_height_without_explicit_parent_height.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\test_percentage_padding_relative_to_container_width.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\Margins\test_auto_margins_center_element_horizontally.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\Margins\test_auto_margins_center_within_padded_container.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\Margins\test_auto_margins_no_explicit_width_fill_container.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\Margins\test_margin_collapse_with_first_child.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\Margins\test_negative_margins_allow_overlap.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\Margins\test_only_left_margin_auto.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\Margins\test_only_right_margin_auto.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\Margins\test_child_wider_than_container_auto_margins.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\Margins\test_empty_block_still_collapses_margins.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\Margins\test_block_element_takes_full_container_width.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\Margins\test_multiple_sibling_margin_collapse.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\Margins\test_nested_margin_collapse_with_parent_and_siblings.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\Margins\test_single_child_margin_collapse.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\BoxSizing\test_box_sizing_auto_width_border_box.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\BoxSizing\test_box_sizing_border_box.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\BoxSizing\test_box_sizing_border_box_includes_border_padding.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\BoxSizing\test_box_sizing_content_box.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\BoxSizing\test_box_sizing_default.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\BoxSizing\test_box_sizing_edge_case_clamped.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\BoxSizing\test_box_sizing_height_border_box.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\BoxSizing\test_box_sizing_height_content_box.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\BoxSizing\test_box_sizing_nested_elements.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
      <None Update="TestData\BoxSizing\test_box_sizing_with_min_max.html">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </None>
    </ItemGroup>

</Project>
